#! /bin/sh

ln -s -f ~/.dotfiles/.vimrc ~/.vimrc
ln -s -f ~/.dotfiles/.gitconfig ~/.gitconfig

mkdir -p ~/.claude
ln -s -f ~/.dotfiles/CLAUDE.md ~/.claude/CLAUDE.md
ln -s -f ~/.dotfiles/claude-settings.json ~/.claude/settings.json

ln -s -f ~/.dotfiles/.zshrc ~/.zshrc
ln -s -f ~/.dotfiles/.gitignore_global ~/.gitignore_global
